var res = {
    HelloWorld_png : "res/HelloWorld.png",
    boton_jugar_png : "res/boton_jugar.png",
    menu_titulo_png : "res/menu_titulo.png",
    jugador_png: "res/jugador/jugador.png",
    jugador_plist: "res/jugador/jugador.plist",
    eevee_png: "res/pokemon/eevee_imagen.png",
    eevee_plist: "res/pokemon/eevee.plist",
    eevee_idle_png: "res/pokemon/eevee_idle.png",
    eevee_idle_plist: "res/pokemon/eevee_idle.plist",
    pikachu_idle_png: "res/pokemon/pikachu_idle.png",
    pikachu_idle_plist: "res/pokemon/pikachu_idle.plist",
    animacion_cuervo_png: "res/animacion_cuervo.png",
    animacion_cuervo_plist: "res/animacion_cuervo.plist",
    caballero_png: "res/jugador/caballero.png",
    caballero_plist: "res/jugador/caballero.plist",
    tiles_mapa: "res/mapas/tiles-mapa.png",
    mapa: "res/mapas/mapa.tmx",
    fondo_lucha_1: "res/fondoLucha/fondo1.png",
    fondo_mensaje_prohibido_gimnasio: "res/fondoMensajes/mensaje_prohibido_gimnasio.png",
    inside_tiles: "res/mapas/inside_tiles.png",
    mapa_gimnasio: "res/mapas/mapa_gimnasio.tmx",
    mensaje_inscripcion_torneo: "res/fondoMensajes/mensaje_apuntar_torneo.png",
    mensaje_ataques_pikachu: "res/fondoMensajes/mensaje_ataques_pikachu.png",
    video: "res/video.mp4",
    disparo_jugador_png: "res/pokemon/disparo_jugador.png",
    disparo_jugador_plist: "res/pokemon/disparo_jugador.plist",
    bola_fuego_png: "res/pokemon/bola_fuego.png",
    bola_fuego_plist: "res/pokemon/bola_fuego.plist",
    mensaje_pokemon_caido_combate: "res/fondoMensajes/mensaje_pokemon_caido_combate.png",
    mensaje_pokemon_derrotados: "res/fondoMensajes/mensaje_pokemon_derrotados.png",
    nurse_png: "res/extra/nurse.png",
    tiles_pokemon_centro: "res/mapas/tiles_pokemon_centro.png",
    mapa_centro_pokemon: "res/mapas/mapa_centro_pokemon.tmx",
    mensaje_curar_pokemon: "res/fondoMensajes/mensaje_curar_pokemon.png",
    mensaje_pokemon_curados: "res/fondoMensajes/mensaje_pokemon_curados.png",
    mensaje_hasta_otra: "res/fondoMensajes/mensaje_hasta_otra.png",
    rayo_png: "res/pokemon/rayo.png",
    rayo_plist: "res/pokemon/rayo.plist",
    mensaje_subir_nivel: "res/fondoMensajes/mensaje_sube_nivel.png",
    pokeball_png: "res/pokeball/pokeball_sprite.png",
    pokeball_sprite: "res/pokeball/pokeball_sprite.png",
    pokeball_plist: "res/pokeball/pokeball.plist",
    pokeball_volando: "res/pokeball/pokeball_volando.png",
    pokeball_volando_plist: "res/pokeball/pokeball_volando.plist",
    pokeball_cerrada_png: "res/pokeball/pokeball_cerrada.png",
    pokeball_cerrada_plist: "res/pokeball/pokeball_cerrada.plist",
    pokeball_abierta_plist: "res/pokeball/pokeball_abierta.plist",
    pokeball_abierta_png: "res/pokeball/pokeball_abierta.png",
    piplup_idle_png: "res/pokemon/piplup_idle.png",
    piplup_idle_plist: "res/pokemon/piplup_idle.plist",
    bola_agua_png: "res/pokemon/bola_agua.png",
    bola_agua_plist: "res/pokemon/bola_agua.plist",
    mensaje_eevee_huido: "res/fondoMensajes/mensaje_eevee_huido.png",
    mensaje_atrapa_eevee: "res/fondoMensajes/mensaje_atrapa_eevee.png",
    charco_agua_png: "res/pokemon/charco_agua.png",
    charco_agua_plist: "res/pokemon/charco_agua.plist",
    mensaje_ataques_piplup: "res/fondoMensajes/mensaje_ataques_piplup.png",
    mensaje_ataques_eevee: "res/fondoMensajes/mensaje_ataques_eevee.png"

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}